### Metodos estadisticos

In [1]:
import numpy as np
from spicy import stats

* Para ver mas operaciones ir a:
* https://github.com/velkha/ProgramaIA_DS/tree/main/Codigo/Python/CalculadoraStPb
* En la clase: https://github.com/velkha/ProgramaIA_DS/blob/main/Codigo/Python/CalculadoraStPb/main/menus/menus_show.py
* Estan todas las operaciones que hace
No tiene comprobado buen hacer del usuario en caso de querer descargarla/usarla. En caso de querer añadirlo a los selectores de el package "menus"

In [2]:

# Specify the file path
filepath = '../../datasets/MilitarySpending.csv'

# Read the CSV file using numpy
data = np.genfromtxt(filepath, delimiter=',', skip_header=1)

# Print the first 5 rows of the dataset
print(data[:5])

[[1960.     47.35  543.3   180.67]
 [1961.     49.88  563.3   183.69]
 [1962.     54.65  605.1   186.54]
 [1963.     54.56  638.6   189.24]
 [1964.     53.43  685.8   191.89]]


In [4]:
#mean for each col
mean = np.mean(data, axis=0)
print(mean)
print(np.mean(data))

#median
median = np.median(data, axis=0)
print(median)
print(np.median(data))

#mode
mode = stats.mode(data, axis=0)
print(mode)
print(stats.mode(data))


[1990.          324.43557377 7680.18557377  255.03393443]
2562.413770491803
[1990.    295.85 5963.14  249.62]
715.565
ModeResult(mode=array([1960.  ,   54.56,  543.3 ,  180.67]), count=array([1., 2., 1., 1.]))
ModeResult(mode=array([1960.  ,   54.56,  543.3 ,  180.67]), count=array([1., 2., 1., 1.]))


In [5]:
#standard deviation
#second colm
std = np.std(data[:,1])
print(std)
print(np.std(data))

#variance
var = np.var(data[:,1])
print(var)
print(np.var(data))

#max min
max = np.max(data[:,1])
print(max)
print(np.max(data))

min = np.min(data[:,1])
print(min)
print(np.min(data))


233.37964220377617
4425.598871499975
54466.057395162585
19585925.371421847
778.0
21433.22
47.35
47.35
