### COMIENZO NUMPY y Carga de datos


In [5]:
%pip install numpy
%pip install matplotlib
%pip install pandas
%pip install spicy

Note: you may need to restart the kernel to use updated packages.



[notice] A new release of pip is available: 23.0.1 -> 24.0
[notice] To update, run: c:\Users\diego\.pyenv\pyenv-win\versions\3.10.11\python.exe -m pip install --upgrade pip


Note: you may need to restart the kernel to use updated packages.



[notice] A new release of pip is available: 23.0.1 -> 24.0
[notice] To update, run: c:\Users\diego\.pyenv\pyenv-win\versions\3.10.11\python.exe -m pip install --upgrade pip


Note: you may need to restart the kernel to use updated packages.



[notice] A new release of pip is available: 23.0.1 -> 24.0
[notice] To update, run: c:\Users\diego\.pyenv\pyenv-win\versions\3.10.11\python.exe -m pip install --upgrade pip


     ---------------------------------------- 0.0/46.2 MB ? eta -:--:--
     ---------------------------------------- 0.4/46.2 MB 11.6 MB/s eta 0:00:04
     - -------------------------------------- 1.6/46.2 MB 20.0 MB/s eta 0:00:03
     -- ------------------------------------- 2.8/46.2 MB 22.1 MB/s eta 0:00:02
     --- ------------------------------------ 4.4/46.2 MB 25.2 MB/s eta 0:00:02
     ---- ----------------------------------- 5.5/46.2 MB 25.2 MB/s eta 0:00:02
     ------ --------------------------------- 7.6/46.2 MB 28.6 MB/s eta 0:00:02
     -------- ------------------------------ 10.3/46.2 MB 32.8 MB/s eta 0:00:02
     ----------- --------------------------- 13.2/46.2 MB 46.7 MB/s eta 0:00:01
     ------------- ------------------------- 16.4/46.2 MB 59.5 MB/s eta 0:00:01
     ---------------- ---------------------- 19.7/46.2 MB 65.6 MB/s eta 0:00:01
     ------------------- ------------------- 23.3/46.2 MB 72.6 MB/s eta 0:00:01
     ---------------------- ---------------- 26.


[notice] A new release of pip is available: 23.0.1 -> 24.0
[notice] To update, run: c:\Users\diego\.pyenv\pyenv-win\versions\3.10.11\python.exe -m pip install --upgrade pip


In [1]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

In [4]:

# Specify the file path
filepath = '../../datasets/MilitarySpending.csv'

# Read the CSV file using numpy
data = np.genfromtxt(filepath, delimiter=',', skip_header=1)

# Print the first 5 rows of the dataset
print(data[:5])


[[1960.     47.35  543.3   180.67]
 [1961.     49.88  563.3   183.69]
 [1962.     54.65  605.1   186.54]
 [1963.     54.56  638.6   189.24]
 [1964.     53.43  685.8   191.89]]
