### COMIENZO NUMPY y Carga de datos


In [ ]:
%pip install numpy
%pip install matplotlib
%pip install pandas


In [1]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

In [4]:

# Specify the file path
filepath = '../../datasets/MilitarySpending.csv'

# Read the CSV file using numpy
data = np.genfromtxt(filepath, delimiter=',', skip_header=1)

# Print the first 5 rows of the dataset
print(data[:5])


[[1960.     47.35  543.3   180.67]
 [1961.     49.88  563.3   183.69]
 [1962.     54.65  605.1   186.54]
 [1963.     54.56  638.6   189.24]
 [1964.     53.43  685.8   191.89]]
