### Operaciones

* Para ver mas operaciones ir a:
* https://github.com/velkha/ProgramaIA_DS/tree/main/Codigo/Python/CalculadoraStPb
* En la clase: https://github.com/velkha/ProgramaIA_DS/blob/main/Codigo/Python/CalculadoraStPb/main/menus/menus_show.py
* Estan todas las operaciones que hace
No tiene comprobado buen hacer del usuario en caso de querer descargarla/usarla. En caso de querer añadirlo a los selectores de el package "menus"

In [1]:
import numpy as np

In [2]:

# path to the dataset
filepath = '../../datasets/MilitarySpending.csv'

# csv with numpy
headers = np.genfromtxt(filepath, delimiter=',', max_rows=1, dtype=str)
data = np.genfromtxt(filepath, delimiter=',', skip_header=1)

# Print the first 5 rows of the dataset
print(headers)
print(data[:5])

['Year' 'DefenseBudget' 'GDP' 'Population']
[[1960.     47.35  543.3   180.67]
 [1961.     49.88  563.3   183.69]
 [1962.     54.65  605.1   186.54]
 [1963.     54.56  638.6   189.24]
 [1964.     53.43  685.8   191.89]]


In [5]:
data1 = data[1, :]
data2 = data[2, :]
data3 = data[3, :]
data4 = data[4, :]
data5 = data[5, :]
data6 = data[6, :]

In [11]:
#sum
print("sum", data1 + data2 + data3 + data4 + data5 + data6)
#substraction
print("substraction", data1 - data2 - data3 - data4 - data5 - data6)
#prod
print("prod", data1 * data2 * data3 * data4 * data5 * data6)
#div
print("div", data1 / data2 / data3 / data4 / data5 / data6)

sum [11781.     333.52  4051.5   1142.22]
substraction [-7859.    -233.76 -2924.9   -774.84]
prod [5.73039353e+19 2.88058127e+10 9.04791870e+16 4.75215626e+13]
div [6.71074504e-14 8.63719565e-08 3.50696001e-12 7.10035913e-10]


In [12]:
#cumsum (cumulative sum)
print("cumsum", data1.cumsum())
#cumprod (cumulative product)
print("cumprod", data1.cumprod())
#cumdiv (cumulative division)
print("cumdiv", data1.cumprod())

cumsum [1961.   2010.88 2574.18 2757.87]
cumprod [1.96100000e+03 9.78146800e+04 5.50990092e+07 1.01211370e+10]
cumdiv [1.96100000e+03 9.78146800e+04 5.50990092e+07 1.01211370e+10]


In [13]:
#square root
print("Square: ",np.sqrt(data1))
#cubic root
print("cubic", np.cbrt(data1))
#exponential
#print(np.exp(data1)) overrflow
#logarithm
print("log", np.log(data1))

# Set a maximum value for elements in data1
max_value = 100
data1_clipped = np.clip(data1, a_min=None, a_max=max_value)
print("expon", np.exp(data1_clipped))

#sin
print("sin", np.sin(data1))
#cos
print("cos", np.cos(data1))

Square:  [44.28317965  7.06257743 23.73394194 13.5532284 ]
cubic [12.51677747  3.68108191  8.25872966  5.68453797]
log [7.58120983 3.90962012 6.33381235 5.21324955]
expon [2.68811714e+43 4.59842129e+21 2.68811714e+43 2.68811714e+43]
sin [ 0.60214428 -0.37600623 -0.81626465  0.99566279]
cos [ 0.79838729  0.92661713 -0.57767814  0.0930355 ]


In [18]:
data_algLin = data[1:4, 1:4]
data_algLin2 = data[4:7, 1:4]
data_algLin3 = data[7:11, 1:4]
data_algLin4 = data[11:14, 1:4]

print(data_algLin)
print(data_algLin2)
print(data_algLin3)
print(data_algLin4)


[[ 49.88 563.3  183.69]
 [ 54.65 605.1  186.54]
 [ 54.56 638.6  189.24]]
[[ 53.43 685.8  191.89]
 [ 54.56 743.7  194.3 ]
 [ 66.44 815.   196.56]]
[[  78.4   861.7   198.71]
 [  84.33  942.5   200.71]
 [  84.99 1019.9   202.68]
 [  83.41 1073.3   205.05]]
[[  78.24 1164.85  207.66]
 [  80.71 1279.11  209.9 ]
 [  81.47 1425.38  211.91]]


In [ ]:
# Scalar product
print("Scalar product: ", np.dot(data_algLin, data_algLin2))
# Cross product
print("Cross product: ", np.cross(data_algLin, data_algLin2))
# Matrix multiplication
print("Matrix multiplication: ", np.matmul(data_algLin, data_algLin2))
#Inverse
print("Inverse: ", np.linalg.inv(data_algLin))
#Determinant
print("Determinant: ", np.linalg.det(data_algLin))
#Eigenvalues and eigenvectors
r, q = np.linalg.eig(data_algLin)
print("Eigenvalues: ", r)
print("Eigenvectors: ", q)
