### Agrupacion de datos

In [1]:
import numpy as np

In [7]:

# path to the dataset
filepath = '../../datasets/MilitarySpending.csv'

# csv with numpy
headers = np.genfromtxt(filepath, delimiter=',', max_rows=1, dtype=str)
data = np.genfromtxt(filepath, delimiter=',', skip_header=1)

# Print the first 5 rows of the dataset
print(headers)
print(data[:5])

['Year' 'DefenseBudget' 'GDP' 'Population']
[[1960.     47.35  543.3   180.67]
 [1961.     49.88  563.3   183.69]
 [1962.     54.65  605.1   186.54]
 [1963.     54.56  638.6   189.24]
 [1964.     53.43  685.8   191.89]]


In [11]:
#print second colmn
print(data[:, 1])
#print first colmn
print(data[0,:])
#print 3 first rows 2 columns
print(data[:3, :2])

[ 47.35  49.88  54.65  54.56  53.43  54.56  66.44  78.4   84.33  84.99
  83.41  78.24  80.71  81.47  89.28  92.08  94.72 104.67 113.38 126.88
 143.69 176.56 221.67 223.43 245.15 272.16 295.55 304.09 309.66 321.87
 325.13 299.37 325.03 316.72 308.08 295.85 287.96 293.17 291.   298.09
 320.09 331.81 378.46 440.53 493.   533.2  558.34 589.59 656.76 705.92
 738.01 752.29 725.21 679.23 647.79 633.83 639.86 646.75 682.49 731.75
 778.  ]
[1960.     47.35  543.3   180.67]
[[1960.     47.35]
 [1961.     49.88]
 [1962.     54.65]]


In [10]:

#? Esto no va a tener sentido pero simplemente por dejarlo hecho
data_flatten = data.flatten()
print(data_flatten)

#! NANI!
data_reshape = data_flatten.reshape(61, 4)
print(data_reshape)


[ 1960.      47.35   543.3    180.67  1961.      49.88   563.3    183.69
  1962.      54.65   605.1    186.54  1963.      54.56   638.6    189.24
  1964.      53.43   685.8    191.89  1965.      54.56   743.7    194.3
  1966.      66.44   815.     196.56  1967.      78.4    861.7    198.71
  1968.      84.33   942.5    200.71  1969.      84.99  1019.9    202.68
  1970.      83.41  1073.3    205.05  1971.      78.24  1164.85   207.66
  1972.      80.71  1279.11   209.9   1973.      81.47  1425.38   211.91
  1974.      89.28  1545.24   213.85  1975.      92.08  1684.9    215.97
  1976.      94.72  1873.41   218.04  1977.     104.67  2081.83   220.24
  1978.     113.38  2351.6    222.58  1979.     126.88  2627.33   225.06
  1980.     143.69  2857.31   227.22  1981.     176.56  3207.04   229.47
  1982.     221.67  3343.79   231.66  1983.     223.43  3634.04   233.79
  1984.     245.15  4037.61   235.82  1985.     272.16  4338.98   237.92
  1986.     295.55  4579.63   240.13  1987.     304.