### Ordenaciones y busquedas

In [2]:
import numpy as np

In [3]:

# Specify the file path
filepath = '../../datasets/MilitarySpending.csv'

# Read the CSV file using numpy
data = np.genfromtxt(filepath, delimiter=',', skip_header=1)

# Print the first 5 rows of the dataset
print(data[:5])

[[1960.     47.35  543.3   180.67]
 [1961.     49.88  563.3   183.69]
 [1962.     54.65  605.1   186.54]
 [1963.     54.56  638.6   189.24]
 [1964.     53.43  685.8   191.89]]


In [9]:
databi1 = data[1:10, 1:8]
datam = data[1:10, 1]
print(databi1)
print(datam)

[[  49.88  563.3   183.69]
 [  54.65  605.1   186.54]
 [  54.56  638.6   189.24]
 [  53.43  685.8   191.89]
 [  54.56  743.7   194.3 ]
 [  66.44  815.    196.56]
 [  78.4   861.7   198.71]
 [  84.33  942.5   200.71]
 [  84.99 1019.9   202.68]]
[49.88 54.65 54.56 53.43 54.56 66.44 78.4  84.33 84.99]


In [12]:
#randomize order of array values
np.random.shuffle(datam)
print(datam)
#np.sort(datam)
datam.sort()
print(datam)

np.random.shuffle(databi1)
print(databi1)
databi1.sort(axis=0)
print(databi1)
databi1.sort(axis=1)
print(databi1)


[84.99 49.88 78.4  54.56 66.44 53.43 54.56 84.33 54.65]
[49.88 53.43 54.56 54.56 54.65 66.44 78.4  84.33 84.99]
[[  84.99  638.6   189.24]
 [  66.44  942.5   200.71]
 [  78.4   605.1   186.54]
 [  54.56  743.7   194.3 ]
 [  84.33  685.8   191.89]
 [  49.88 1019.9   202.68]
 [  53.43  861.7   198.71]
 [  54.56  563.3   183.69]
 [  54.65  815.    196.56]]
[[  49.88  563.3   183.69]
 [  53.43  605.1   186.54]
 [  54.56  638.6   189.24]
 [  54.56  685.8   191.89]
 [  54.65  743.7   194.3 ]
 [  66.44  815.    196.56]
 [  78.4   861.7   198.71]
 [  84.33  942.5   200.71]
 [  84.99 1019.9   202.68]]
[[  49.88  183.69  563.3 ]
 [  53.43  186.54  605.1 ]
 [  54.56  189.24  638.6 ]
 [  54.56  191.89  685.8 ]
 [  54.65  194.3   743.7 ]
 [  66.44  196.56  815.  ]
 [  78.4   198.71  861.7 ]
 [  84.33  200.71  942.5 ]
 [  84.99  202.68 1019.9 ]]


In [16]:
min = np.argmin(datam)
max = np.argmax(datam)
print(min)
print(max)
dataFiltered  = datam[(datam > 40) & (datam < 60)]
print(dataFiltered)
dataFiltered2  = np.where(datam > 50)
print(dataFiltered2)
dataFiltered3  = np.where(datam > 50, 'yes', 'no')
print(dataFiltered3)


0
8
[49.88 53.43 54.56 54.56 54.65]
(array([1, 2, 3, 4, 5, 6, 7, 8], dtype=int64),)
['no' 'yes' 'yes' 'yes' 'yes' 'yes' 'yes' 'yes' 'yes']
